---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fail2ban
  namespace: fail2ban

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fail2ban
rules:
- apiGroups: ["crd.projectcalico.org"]
  resources: ["globalnetworksets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fail2ban
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fail2ban
subjects:
  - kind: ServiceAccount
    name: fail2ban
    namespace: fail2ban
